#################################################
# General Config
#################################################
default_config:
homeassistant:
  allowlist_external_dirs:
    - /tmp
  # customize: !include_dir_merge_named customize/
  elevation: !secret elevation
  latitude: !secret latitude
  longitude: !secret longitude
  name: Annacar Home
  time_zone: !secret time_zone
  unit_system: !secret unit_system
  country: US
  currency: USD

#################################################
# Enable Services
#################################################
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: error
  logs:
    pychromecast.socket_client: fatal
    homeassistant.components.stream.stream.camera.bedroom_camera: fatal
    homeassistant.components.stream.stream.camera.office_camera: fatal
    homeassistant.components.stream.stream.camera.living_room_camera: fatal
    homeassistant.components.stream.stream.camera.dining_room_camera: fatal

python_script:

recorder:
  db_url: !secret db_url

zha:
  zigpy_config:
    source_routing: true

stream:

#################################################
# Include External Scripts
#################################################
aarlo: !include /config/aarlo/aarlo.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

template: !include_dir_merge_list templates/
group: !include_dir_merge_named groups/
notify: !include_dir_merge_list notifications/
