- platform: group
  name: Bedroom Lights
  unique_id: "b3e17b50-bf3c-11ec-9d64-0242ac120002"
  entities:
    - light.bedroom_bedside_lamps
    - light.bedroom_floor_lamp
    - light.bedroom_dresser_lamp

- platform: group
  name: Dining Room Lights
  unique_id: "93d7ecfb-3e24-437a-a819-ae258d9d73ca"
  entities:
    - light.dining_room_floor_lamp_1
    - light.dining_room_floor_lamp_2

- platform: group
  name: Living Room TV
  unique_id: "a599729c-0f76-44ab-9da1-07c76bc0fd5e"
  entities:
    - light.living_room_tv_left_lamp
    - light.living_room_tv_right_lamp
    - light.living_room_light_bar_1
    - light.living_room_light_bar_2

- platform: group
  name: Living Room Lights
  unique_id: "3a2917fb-4dc5-4629-a717-c4e447d8a206"
  entities:
    - light.living_room_tv

- platform: group
  name: Downstairs Lights
  unique_id: "bb4a9027-8aec-49b7-975f-e80ba4aab17a"
  entities:
    - light.living_room_lights

- platform: group
  name: Office Lights
  unique_id: "da6e55a4-a3d0-49e2-ac57-129631fb132c"
  entities:
    - light.office_lamp
    - light.iris
