#################################################
# Doors & Motion
#################################################
- alias: Back Deck Floodlight
  id: 627e6d5d-ff83-495d-a2a5-ce3b281a1b49
  description: "Turns on back deck flood light when the patio door is opened or motion is detected in the back yard if it is night time"
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.aarlo_motion_south_backyard
      from:
        - "off"
      to:
        - "on"
    - trigger: state
      entity_id:
        - binary_sensor.aarlo_motion_north_backyard
      from:
        - "off"
      to:
        - "on"
    - trigger: state
      entity_id:
        - binary_sensor.patio_door
      from:
        - "off"
      to:
        - "on"
  conditions:
    - condition: state
      entity_id: sun.sun
      state:
        - below_horizon
  actions:
    - action: light.turn_on
      metadata: {}
      target:
        entity_id: light.back_deck_floodlight
      data: {}
    - delay:
        hours: 0
        minutes: 10
        seconds: 0
        milliseconds: 0
    - action: light.turn_off
      metadata: {}
      target:
        entity_id: light.back_deck_floodlight
      data: {}
  mode: restart
