#################################################
# Motion
#################################################
- alias: Breezeway Motion
  triggers:
    - trigger: state
      entity_id: binary_sensor.aarlo_motion_breezeway
      from: "off"
      to: "on"
  actions:
    - action: light.turn_on
      entity_id: light.breezeway_doors
  condition:
    alias: "Sun down"
    condition: state
    entity_id: sun.sun
    state: "below_horizon"
  mode: single

- alias: Breezeway Idle
  triggers:
    - trigger: state
      entity_id: binary_sensor.aarlo_motion_breezeway
      to: "off"
      for: "00:10:00"
  actions:
    - action: light.turn_off
      entity_id: light.breezeway_doors
  mode: single

#################################################
# Door Open
#################################################
- alias: Laundry Room Door Open
  triggers:
    - trigger: state
      entity_id: binary_sensor.laundry_room_door
      from: "off"
      to: "on"
  actions:
    - action: light.turn_on
      entity_id: light.breezeway_doors
    - action: switch.turn_on
      entity_id: switch.back_driveway_floodlight
  condition:
    alias: "Sun down"
    condition: state
    entity_id: sun.sun
    state: "below_horizon"
  mode: single

- alias: Laundry Room Door Closed
  triggers:
    - trigger: state
      entity_id: binary_sensor.laundry_room_door
      from: "on"
      to: "off"
      for: "00:10:00"
  actions:
    - action: light.turn_off
      entity_id: light.breezeway_doors
  condition:
    alias: "Sun down"
    condition: state
    entity_id: sun.sun
    state: "below_horizon"
  mode: single
