#################################################
# Door Open / Close
#################################################
- alias: Front Door Open
  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
  actions:
    - action: light.turn_on
      entity_id: light.front_door_lights
  mode: single

- alias: Front Door Closed
  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door
      to: "off"
      for: "00:01:00"
  actions:
    - action: light.turn_off
      entity_id: light.front_door_lights
  mode: single
