#################################################
# General
#################################################
- alias: "Sun Rise"
  triggers:
    trigger: sun
    event: sunrise
    offset: "+00:00:00"
  actions:
    - action: switch.turn_off
      entity_id: switch.front_porch
    - action: switch.turn_off
      entity_id: switch.front_driveway_lights
    - action: switch.turn_off
      entity_id: switch.front_porch_strips_power_switch

- alias: "Sun Set"
  triggers:
    trigger: sun
    event: sunset
    offset: "+00:00:00"
  actions:
    - action: switch.turn_on
      entity_id: switch.front_porch
    - action: switch.turn_on
      entity_id: switch.front_driveway_lights
    - action: switch.turn_on
      entity_id: switch.front_porch_strips_power_switch

#################################################
# Location & Alarms
#################################################
- alias: Arm Away
  triggers:
    trigger: state
    entity_id: group.family_tracker
    from: "home"
    to: "not_home"
    for:
      seconds: 60
  condition: []
  actions:
    - action: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.aarlo_annacar_arlo
    - action: notify.all_personal_devices
      data:
        message: Everyone has left. Activating Away Mode.
    - action: scene.turn_on
      entity_id: scene.away
  mode: single

- alias: Arm Home
  triggers:
    trigger: state
    entity_id: group.family_tracker
    from: "not_home"
    to: "home"
    for:
      seconds: 10
  condition: []
  actions:
    - action: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.aarlo_annacar_arlo
    - action: notify.all_personal_devices
      data:
        message: Arriving Home
    - action: scene.turn_on
      entity_id: scene.arriving_home
  mode: single

# - alias: Carson Driving Home
#   triggers:
#     trigger: state
#     entity_id: device_tracker.carson_phone
#     from: "not_home"
#     to: "home"
#   condition: "{{ is_state('input_select.carson_status', 'carson_driving') }}"
#   actions:
#     - action: cover.open_cover
#       entity_id: cover.garage_bay_2
#     - action: input_select.select_option
#       data:
#         option: carson_home
#       target:
#         entity_id: input_select.carson_status

# - alias: Anna Driving Home
#   triggers:
#     trigger: state
#     entity_id: device_tracker.anna_phone
#     from: "not_home"
#     to: "home"
#   condition: "{{ is_state('input_select.anna_status', 'anna_driving') }}"
#   actions:
#     - action: cover.open_cover
#       entity_id: cover.garage_bay_1
#     - action: input_select.select_option
#       data:
#         option: anna_home
#       target:
#         entity_id: input_select.anna_status

#################################################
#  Tags
#################################################
- alias: Front Door Is Tagged
  triggers:
    - trigger: tag
      tag_id: f849630c-64f4-4f6a-ba15-9e4fb22c411a
  condition: []
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id: lock.front_door_lock
              state: locked
          sequence:
            - action: lock.unlock
              entity_id: lock.front_door_lock
        - conditions:
            - condition: state
              entity_id: lock.front_door_lock
              state: unlocked
          sequence:
            - action: lock.lock
              entity_id: lock.front_door_lock
  mode: single

#################################################
# House State
#################################################
- alias: Lock Doors
  triggers:
    - trigger: state
      entity_id: input_select.house_state
      to: "away"
    - trigger: state
      entity_id: input_select.house_state
      to: "night"
  condition: []
  actions:
    - action: script.lock_doors
