#######################
# Media Scenes
#######################
- alias: Plex Play
  triggers:
    - trigger: state
      entity_id: media_player.living_room_plex
      from: idle
      to: playing
    - trigger: state
      entity_id: media_player.living_room_plex
      from: paused
      to: playing
    - trigger: state
      entity_id: media_player.plex_infuse_living_room
      from: idle
      to: playing
    - trigger: state
      entity_id: media_player.plex_infuse_living_room
      from: paused
      to: playing
  condition: []
  actions:
    - action: scene.turn_on
      entity_id: scene.movie_time
  mode: single

- alias: Plex Paused
  triggers:
    - trigger: state
      entity_id: media_player.living_room_plex
      from: playing
      to: paused
    - trigger: state
      entity_id: media_player.plex_infuse_living_room
      from: playing
      to: paused
  condition: []
  actions:
    - action: scene.turn_on
      entity_id: scene.movie_time_paused
  mode: single

- alias: Kitchen Controller
  mode: queued
  max_exceeded: silent
  triggers:
    - trigger: event
      event_type: zha_event
      event_data:
        device_id: 03f2a8fc68acb2cc66e1f44da37c3515
  actions:
    - variables:
        command: "{{ triggers.event.data.command }}"
    - choose:
        - conditions:
            - "{{ command == 'on' }}"
          sequence:
            - action: light.toggle
              entity_id: light.kitchen_lights
        - conditions:
            - "{{ command == 'off' }}"
          sequence:
            - action: light.toggle
              entity_id: light.dining_room_lights
