#################################################
# carson-mac
#################################################
- alias: Office Carson Mac Screen On
  trigger:
    - platform: state
      entity_id: sensor.carson_mac_screen_off
      from: "True"
      to: "False"
  action:
    - service: switch.turn_on
      entity_id: switch.office_studio_monitors

  mode: single

- alias: Office Carson Mac Screen Off
  trigger:
    - platform: state
      entity_id: sensor.carson_mac_screen_off
      from: "False"
      to: "True"
      for: "00:30:00"
  action:
    - service: switch.turn_off
      entity_id: switch.office_studio_monitors
  mode: single

- alias: Office Carson Mac Webcam On
  trigger:
    - platform: state
      entity_id: binary_sensor.carson_mac_camera_in_use
      to: "on"
  action:
    - service: input_select.select_option
      data:
        option: meeting
      target:
        entity_id: input_select.office_state
  mode: queued

- alias: Office Carson Mac Webcam Off
  trigger:
    - platform: state
      entity_id: binary_sensor.carson_mac_camera_in_use
      from: "on"
      to: "off"
  action:
    - service: input_select.select_option
      data:
        option: normal
      target:
        entity_id: input_select.office_state
  mode: queued

#################################################
# Motion
#################################################
- alias: Office Occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_occupancy
      to: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.office_active_day

- alias: Office Vacant
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_occupancy
      to: "off"
      for: "01:00:00"
  action:
    - service: scene.turn_on
      entity_id: scene.office_inactive

- alias: Office Bathroom Occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.office_bathroom_occupancy
      from: "off"
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.office_bathroom

- alias: Office Bathroom Vacant
  trigger:
    - platform: state
      entity_id: binary_sensor.office_bathroom_occupancy
      to: "off"
      for: "00:15:00"
  action:
    - service: light.turn_off
      entity_id: light.office_bathroom

- alias: Office Stairs Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.office_stairs_motion
      from: "off"
      to: "on"
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.office_state', 'meeting') }}"
          sequence:
            - service: light.turn_on
              data:
                brightness: 255
                rgb_color: [255, 0, 0]
                entity_id: light.office_stairs
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.office_state', 'normal') }}"
          sequence:
            - service: light.turn_on
              data:
                brightness: 255
                rgb_color: [255, 255, 255]
                entity_id: light.office_stairs
      default:
        - service: light.turn_on
          data:
            brightness: 255
            rgb_color: [255, 255, 255]
            entity_id: light.office_stairs

- alias: Office Stairs Idle
  trigger:
    - platform: state
      entity_id: binary_sensor.office_stairs_motion
      to: "off"
      for: "00:2:00"
  action:
    - service: light.turn_off
      entity_id: light.office_stairs
